### PR TITLE
Policy Matching

### LINKED ISSUE #62: Backend: Policy Matching
Specification pattern + first only use Measurement Resolution + Price for matching + Contract creation on match

### PR DESCRIPTION
**Pull request by Smightym8**
- **feat(specifications): implement policy specifications with tests**
  - Added `PriceSpecification` to filter policies based on maximum price.
  - Added `MeasurementResolutionSpecification` to filter policies by measurement resolution.
  - Implemented `PolicyMatchesRequestSpecification` to combine multiple criteria for matching policies with requests.
  - Moved Entity Unit Tests into Model folder and created Specifications Folder for Specification Unit Tests
  - Wrote unit tests for `PriceSpecification`, `MeasurementResolutionSpecification`, and `PolicyMatchesRequestSpecification` to validate correct behavior.
  

- **feat(policy-matching): implement matching policies based on policy request**
  - Refactored CreatePolicyRequestEndpoint to return a List of PolicyDtos
  - Refactored PolicyRequestCreateService to find matching policies and returning them.
  - Added GetAll method in TenantRepository to get all tenants
  - Added GetPoliciesByTenantAsync to get all policies of a tenant
  - Updated unit and integration tests.
  

- **refactor(policy-matching): extract matching logic into own service**
  - Created PolicyMatchingService and moved matching logic into this service
  - Created GetMatchingPoliciesEndpoint to get matching policies for an existing policy request
  - Refactored PolicyRequestCreateService to use PolicyMatchingService to get matching policies
  - Added new unit and integration tests and updated existing tests that are affected by the changes.

### CODE REVIEW

**Review by 1r-1na — COMMENTED** [review]
I get an exception when creating a new policy with
```JSON
{
  "measurementResolution": "Raw",
  "locationResolution": "None",
  "price": 0,
  "smartMeterId": "27488a2b-c8af-43a7-b829-ddd606e818d0"
}
```
I need to change `measurementResolution` and `locationResolution` to a number of the enum.
Either we change the API description or it has to be fixed.
image

Same with policy request.

**Comment by iiNomad23** [comment]
> I get an exception when creating a new policy with
> 
> ```json
> {
>   "measurementResolution": "Raw",
>   "locationResolution": "None",
>   "price": 0,
>   "smartMeterId": "27488a2b-c8af-43a7-b829-ddd606e818d0"
> }
> ```
> 
> I need to change `measurementResolution` and `locationResolution` to a number of the enum. Either we change the API description or it has to be fixed. image
> 
> Same with policy request.

This has already been fixed and is included in the main branch.

**Comment by 1r-1na** [comment]
> > I get an exception when creating a new policy with
> > ```json
> > {
> >   "measurementResolution": "Raw",
> >   "locationResolution": "None",
> >   "price": 0,
> >   "smartMeterId": "27488a2b-c8af-43a7-b829-ddd606e818d0"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I need to change `measurementResolution` and `locationResolution` to a number of the enum. Either we change the API description or it has to be fixed. image
> > Same with policy request.
> 
> This has already been fixed and is included in the main branch.

So you mean main branch has to be merged and then it should work? @Smightym8 can you merge it?

**Comment by Smightym8** [comment]
> > > I get an exception when creating a new policy with
> > > ```json
> > > {
> > >   "measurementResolution": "Raw",
> > >   "locationResolution": "None",
> > >   "price": 0,
> > >   "smartMeterId": "27488a2b-c8af-43a7-b829-ddd606e818d0"
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I need to change `measurementResolution` and `locationResolution` to a number of the enum. Either we change the API description or it has to be fixed. image
> > > Same with policy request.
> > 
> > 
> > This has already been fixed and is included in the main branch.
> 
> So you mean main branch has to be merged and then it should work? @Smightym8 can you merge it?

It is already merged

**Review by Essiga — APPROVED** [review]
lgtm

**Pull request merged**
